#!/usr/bin/env python
__author__ = 'Matias Carrasco Kind'
import os, sys
path_src = os.path.abspath(os.path.join(os.path.dirname(__file__), '../../'))
if not path_src in sys.path: sys.path.insert(1, path_src)
from mlz.utils import *
import mlz.plot.plotting as pl

if len(sys.argv) < 2:
    utils_mlz.printpz()
    utils_mlz.printpz("Usage:: ")
    utils_mlz.printpz("---------------------------------------")
    utils_mlz.printpz("./plot_tree <input file> <tree number> ")
    utils_mlz.printpz("---------------------------------------")
    utils_mlz.printpz()
    utils_mlz.printpz("<input file>  : Same used in runMLZ")
    utils_mlz.printpz("<tree number> : default is 0")
    sys.exit(0)

FilePars = sys.argv[1]
Narg=len(sys.argv)
if Narg > 2:
    it=int(sys.argv[2])
else:
    it=0
Q = pl.Qplot(FilePars)
Q.plot_tree(it)
